import 'package:flutter/material.dart';

const redAccent = Color.fromARGB(255, 148, 46, 39);

Map<String, Map<String, dynamic>> data = {
  "order_confirmation": {
    "name": "ORDER CONFIRMATION",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "fit_sample_approval": {
    "name": "FIT SAMPLE APPROVAL",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "lab_dip_approval": {
    "name": "LAB DIP APPROVAL",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "bulk_trims_approval": {
    "name": "BULK TRIMS APPROVAL",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "pp_sample_approval": {
    "name": "PP SAMPLE APPROVAL",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "bulk_trim_inhouse": {
    "name": "BULK TRIM INHOUSE",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "bulk_fabric_approval": {
    "name": "BULK FABRIC APPROVAL",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "fabric_inspection": {
    "name": "FABRIC INSPECTION",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "ppm": {
    "name": "PPM",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "pcd": {
    "name": "PCD",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "inline_inspection": {
    "name": "INLINE INSPECTION",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "midline_inspection": {
    "name": "MIDLINE INSPECTION",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "final_inspection": {
    "name": "FINAL INSPECTION",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
  "ex_factory": {
    "name": "EX FACTORY",
    "isDocUploaded": false,
    "isRquiredApproval": false,
    "isRquiredDueDate": false,
    "dueDate": "--/--/----",
    "actualDate": "--/--/----",
    "comments": [],
  },
};

var dataList = [
  {"id": "order_confirmation", "name": "ORDER CONFIRMATION"},
  {"id": "fit_sample_approval", "name": "FIT SAMPLE APPROVAL"},
  {"id": "lab_dip_approval", "name": "LAB DIP/ PRINT S/ OFF APPROVAL"},
  {"id": "bulk_trims_approval", "name": "BULK TRIMS APPROVAL"},
  {"id": "pp_sample_approval", "name": "PP SAMPLE APPROVAL"},
  {"id": "bulk_trim_inhouse", "name": "BULK TRIM INHOUSE"},
  {"id": "bulk_fabric_approval", "name": "BULK FABRIC APPROVAL"},
  {"id": "fabric_inspection", "name": "FABRIC INSPECTION"},
  {"id": "ppm", "name": "PPM"},
  {"id": "pcd", "name": "PCD"},
  {"id": "inline_inspection", "name": "INLINE INSPECTION"},
  {"id": "midline_inspection", "name": "MIDLINE INSPECTION"},
  {"id": "final_inspection", "name": "FINAL INSPECTION"},
  {"id": "ex_factory", "name": "EX FACTORY"},
];
